export const jobTypes = [
  "Permanent",
  "Temporary",
  "Paid Internship",
  "Student / postdoc",
  "AmeriCorps",
  "Unpaid",
];

export const locations = {
  Regions: [
    { value: "region-1", label: "Africa" },
    { value: "region-2", label: "Asia" },
    { value: "region-4", label: "Australia" },
    { value: "region-6", label: "Canada" },
    { value: "region-3", label: "Europe" },
    { value: "region-5", label: "Latin America" },
    { value: "region-8", label: "Other" },
    { value: "region-9", label: "Remote / Flexible" },
  ],
  States: [
    { value: "state-1", label: "Alabama" },
    { value: "state-2", label: "Alaska" },
    { value: "state-3", label: "Arizona" },
    { value: "state-4", label: "Arkansas" },
    { value: "state-5", label: "California" },
    { value: "state-6", label: "Colorado" },
    { value: "state-7", label: "Connecticut" },
    { value: "state-8", label: "Delaware" },
    { value: "state-9", label: "DC" },
    { value: "state-10", label: "Florida" },
    { value: "state-11", label: "Georgia" },
    { value: "state-12", label: "Hawaii" },
    { value: "state-13", label: "Idaho" },
    { value: "state-14", label: "Illinois" },
    { value: "state-15", label: "Indiana" },
    { value: "state-16", label: "Iowa" },
    { value: "state-17", label: "Kansas" },
    { value: "state-18", label: "Kentucky" },
    { value: "state-19", label: "Louisiana" },
    { value: "state-20", label: "Maine" },
    { value: "state-21", label: "Maryland" },
    { value: "state-22", label: "Massachusetts" },
    { value: "state-23", label: "Michigan" },
    { value: "state-24", label: "Minnesota" },
    { value: "state-25", label: "Mississippi" },
    { value: "state-26", label: "Missouri" },
    { value: "state-27", label: "Montana" },
    { value: "state-28", label: "Nebraska" },
    { value: "state-29", label: "Nevada" },
    { value: "state-30", label: "New Hampshire" },
    { value: "state-31", label: "New Jersey" },
    { value: "state-32", label: "New Mexico" },
    { value: "state-33", label: "New York" },
    { value: "state-34", label: "North Carolina" },
    { value: "state-35", label: "North Dakota" },
    { value: "state-36", label: "Ohio" },
    { value: "state-37", label: "Oklahoma" },
    { value: "state-38", label: "Oregon" },
    { value: "state-39", label: "Pennsylvania" },
    { value: "state-41", label: "Rhode Island" },
    { value: "state-42", label: "South Carolina" },
    { value: "state-43", label: "South Dakota" },
    { value: "state-44", label: "Tennessee" },
    { value: "state-45", label: "Texas" },
    { value: "state-46", label: "Utah" },
    { value: "state-47", label: "Vermont" },
    { value: "state-48", label: "Virginia" },
    { value: "state-49", label: "Washington" },
    { value: "state-50", label: "West Virginia" },
    { value: "state-51", label: "Wisconsin" },
    { value: "state-52", label: "Wyoming" },
    { value: "state-53", label: "US Territories" },
  ],
};

export const experienceLevels = [
  { value: "Entry Level", label: "Entry Level (0 - 1 years)" },
  { value: "Mid Level", label: "Mid Level (2 - 6 years)" },
  { value: "High Level", label: "High Level (7+ years)" },
];
