export const jobTypes = [
  "Permanent",
  "Temporary",
  "Paid Internship",
  "Student / postdoc",
  "AmeriCorps",
  "Unpaid",
];

export const locations = {
  Regions: [
    { value: "Africa", label: "Africa" },
    { value: "Asia", label: "Asia" },
    { value: "Australia", label: "Australia" },
    { value: "Canada", label: "Canada" },
    { value: "Europe", label: "Europe" },
    { value: "Latin America", label: "Latin America" },
    { value: "Other", label: "Other" },
    { value: "Remote / Flexible", label: "Remote / Flexible" },
  ],
  States: [
    { value: "Alabama", label: "Alabama" },
    { value: "Alaska", label: "Alaska" },
    { value: "Arizona", label: "Arizona" },
    { value: "Arkansas", label: "Arkansas" },
    { value: "California", label: "California" },
    { value: "Colorado", label: "Colorado" },
    { value: "Connecticut", label: "Connecticut" },
    { value: "Delaware", label: "Delaware" },
    { value: "DC", label: "DC" },
    { value: "Florida", label: "Florida" },
    { value: "Georgia", label: "Georgia" },
    { value: "Hawaii", label: "Hawaii" },
    { value: "Idaho", label: "Idaho" },
    { value: "Illinois", label: "Illinois" },
    { value: "Indiana", label: "Indiana" },
    { value: "Iowa", label: "Iowa" },
    { value: "Kansas", label: "Kansas" },
    { value: "Kentucky", label: "Kentucky" },
    { value: "Louisiana", label: "Louisiana" },
    { value: "Maine", label: "Maine" },
    { value: "Maryland", label: "Maryland" },
    { value: "Massachusetts", label: "Massachusetts" },
    { value: "Michigan", label: "Michigan" },
    { value: "Minnesota", label: "Minnesota" },
    { value: "Mississippi", label: "Mississippi" },
    { value: "Missouri", label: "Missouri" },
    { value: "Montana", label: "Montana" },
    { value: "Nebraska", label: "Nebraska" },
    { value: "Nevada", label: "Nevada" },
    { value: "New Hampshire", label: "New Hampshire" },
    { value: "New Jersey", label: "New Jersey" },
    { value: "New Mexico", label: "New Mexico" },
    { value: "New York", label: "New York" },
    { value: "North Carolina", label: "North Carolina" },
    { value: "North Dakota", label: "North Dakota" },
    { value: "Ohio", label: "Ohio" },
    { value: "Oklahoma", label: "Oklahoma" },
    { value: "Oregon", label: "Oregon" },
    { value: "Pennsylvania", label: "Pennsylvania" },
    { value: "Rhode Island", label: "Rhode Island" },
    { value: "South Carolina", label: "South Carolina" },
    { value: "South Dakota", label: "South Dakota" },
    { value: "Tennessee", label: "Tennessee" },
    { value: "Texas", label: "Texas" },
    { value: "Utah", label: "Utah" },
    { value: "Vermont", label: "Vermont" },
    { value: "Virginia", label: "Virginia" },
    { value: "Washington", label: "Washington" },
    { value: "West Virginia", label: "West Virginia" },
    { value: "Wisconsin", label: "Wisconsin" },
    { value: "Wyoming", label: "Wyoming" },
    { value: "US Territories", label: "US Territories" },
  ],
};

export const experienceLevels = [
  { value: "Entry Level", label: "Entry Level (0 - 1 years)" },
  { value: "Mid Level", label: "Mid Level (2 - 6 years)" },
  { value: "High Level", label: "High Level (7+ years)" },
];

export const categories = [
  { value: "Admin & Leadership", label: "Admin & Leadership" },
  { value: "Botany", label: "Botany" },
  { value: "Ecology", label: "Ecology" },
  { value: "Environmental Education", label: "Environmental Education" },
  { value: "Fisheries", label: "Fisheries" },
  { value: "Forestry", label: "Forestry" },
  { value: "Hydrology", label: "Hydrology" },
  { value: "Land Trust", label: "Land Trust" },
  { value: "Marine Biology", label: "Marine Biology" },
  { value: "General / Stewardship", label: "General / Stewardship" },
  { value: "Policy And Law", label: "Policy And Law" },
  { value: "Outdoor Recreation", label: "Outdoor Recreation" },
  { value: "Restoration", label: "Restoration" },
  { value: "Sustainability", label: "Sustainability" },
  { value: "Wildlife", label: "Wildlife" },
  { value: "Other", label: "Other" },
];
